{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_user_sdk",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6755972,
          "sha512": "da45aab8725c85963f6a03263a867e0e1f881f343f70b6cf8f8ef71df4224673e8185bd6325b406f8e9fb06fda23153dd8359e95ab89ef2d07ac48410a256e94",
          "sha256": "53b7ed07a79a0363a9275a57e64bfecbc52aeeb9d465bb0e32a291e8daa996ba",
          "sha1": "3572eb58f38bd342f3a9f7d668698614ead0a08b",
          "md5": "e2d51563b2f06b828ce203c009cd3de9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-13e658725ddaa270601426d1485636157e38c34c"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6755972,
          "sha512": "da45aab8725c85963f6a03263a867e0e1f881f343f70b6cf8f8ef71df4224673e8185bd6325b406f8e9fb06fda23153dd8359e95ab89ef2d07ac48410a256e94",
          "sha256": "53b7ed07a79a0363a9275a57e64bfecbc52aeeb9d465bb0e32a291e8daa996ba",
          "sha1": "3572eb58f38bd342f3a9f7d668698614ead0a08b",
          "md5": "e2d51563b2f06b828ce203c009cd3de9"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
